# Generated by Django 5.1.1 on 2024-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('coverphoto', models.FileField(upload_to='')),
                ('No_of_copies', models.PositiveIntegerField()),
            ],
        ),
    ]
