# Generated by Django 5.1.1 on 2024-10-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
