# Generated by Django 5.1.1 on 2024-10-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_books_coverphoto'),
        ('student', '0003_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
