# Generated by Django 5.1.1 on 2024-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
